package ai.offside.mobile.android.helper.testlabs.nav.icons.decorative

enum class IconsDecorative (val text:String, val iconResourceId: Int) {
    ICON1("Accept Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_accept_regular),
    ICON2("Accept Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_accept_solid),
    ICON3("Account Approved", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_account_approved),
    ICON4("Account Details", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_account_details),
    ICON5("Account Routing", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_account_routing),
    ICON6("Add Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_add_regular),
    ICON7("Add Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_add_solid),
    ICON8("Add User Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_add_user_regular),
    ICON9("Add User Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_add_user_solid),
    ICON10("Alerts", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_alerts),
    ICON11("Alerts Big Circle", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_alerts_bg_circle),
    ICON12("Arrow Circle", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_arrow_circle),
    ICON13("Atm Access Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_atm_access_regular),
    ICON14("Atm Access Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_atm_access_solid),
    ICON15("Atm Generic", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_atm_generic),
    ICON16("Acme ATM", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_atm_offside),
    ICON17("Bank Building Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_bank_building_regular),
    ICON18("Bank Building Thin", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_bank_building_thin),
    ICON19("Bells", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_bells),
    ICON20("Bill Statement", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_bill_statement),
    ICON21("Book", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_book),
    ICON22("Briefcase Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_briefcase_regular),
    ICON23("Briefcase Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_briefcase_solid),
    ICON24("Briefcase Thin", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_briefcase_thin),
    ICON25("Car", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_car),
    ICON26("Car Front", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_car_front),
    ICON27("Card Placeholder", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_card_placeholder),
    ICON28("Card Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_card_regular),
    ICON29("Card Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_card_solid),
    ICON30("Card Thin", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_card_thin),
    ICON31("Charts Bars", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_charts_bars),
    ICON32("Charts Pie", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_charts_pie),
    ICON33("Charts Progress", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_charts_progress),
    ICON34("Clock Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_clock_solid),
    ICON35("Clock thin", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_clock_thin),
    ICON36("Customize", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_customize),
    ICON37("Direction", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_direction),
    ICON38("Disputes", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_disputes),
    ICON39("Document", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_document),
    ICON40("Ebill", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_ebill),
    ICON41("Enroll", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_enroll),
    ICON42("Exclaimation Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_exclamation_regular),
    ICON43("Exclaimation Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_exclamation_solid),
    ICON44("Facebook", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_facebook),
    ICON45("Fees", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_fees),
    ICON46("Filter", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_filter),
    ICON47("Filter Alt", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_filter_alt),
    ICON48("Group Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_group_regular),
    ICON49("Group Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_group_solid),
    ICON50("Hammer", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_hammer),
    ICON51("Help 2", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_help_2),
    ICON52("History", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_history),
    ICON53("House Check", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_house_check),
    ICON54("House Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_house_regular),
    ICON55("House Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_house_solid),
    ICON56("Id Card Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_id_card_regular),
    ICON57("Id Card Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_id_card_solid),
    ICON58("Information", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_information),
    ICON59("Insights Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_insights_regular),
    ICON60("Insights Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_insights_solid),
    ICON61("Investments Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_investments_regular),
    ICON62("Investments Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_investments_solid),
    ICON63("Link", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_link),
    ICON64("Load Error Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_load_error_regular),
    ICON65("Load Error Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_load_error_solid),
    ICON66("Locations", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_locations),
    ICON67("Locator", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_locator),
    ICON68("Lock Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_lock_regular),
    ICON69("Lock Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_lock_solid),
    ICON70("Mail", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_mail),
    ICON71("Mail Open", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_mail_open),
    ICON72("Make Payment Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_make_payment_regular),
    ICON73("Acme Message", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_message_offside),
    ICON74("Mobile Deposit Camera", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_mobile_deposit_camera),
    ICON75("Mobile Deposit Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_mobile_deposit_regular),
    ICON76("Mobile Phone Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_mobile_phone_regular),
    ICON77("Mobile Phone Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_mobile_phone_solid),
    ICON78("Money Bills Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_money_bills_regular),
    ICON79("Money Bills Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_money_bills_solid),
    ICON80("Overdraft", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_overdraft),
    ICON81("Payee", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_payee),
    ICON82("Payments and Advances", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_payments_and_advances),
    ICON83("Person", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_person),
    ICON84("Personal Loans", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_personal_loans),
    ICON85("Phone", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_phone),
    ICON86("Piggy Bank", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_piggy_bank),
    ICON87("Placeholder Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_placeholder_regular),
    ICON88("Play", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_play),
    ICON89("Protection", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_protection),
    ICON90("Reminders", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_reminders),
    ICON91("Replace Card", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_replace_card),
    ICON92("Request for Payment", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_request_for_payment),
    ICON93("Reset", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_reset),
    ICON94("Rewards Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_rewards_regular),
    ICON95("Rewards Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_rewards_solid),
    ICON96("Schedule", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_schedule),
    ICON97("Security Control Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_security_ctr_regular),
    ICON98("Security Control Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_security_ctr_solid),
    ICON99("Settings Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_settings_regular),
    ICON100("Settings Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_settings_solid),
    ICON101("Shop Alert", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_shop_alert),
    ICON102("Sort Down", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_sort_down),
    ICON103("Sort Up", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_sort_up),
    ICON104("Sorting Up Down", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_sorting_up_down),
    ICON105("Statement Documents Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_statements_document_regular),
    ICON106("Statement Documents Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_statements_documents_solid),
    ICON107("Success", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_success),
    ICON108("Time", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_time),
    ICON109("Transfer", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_transfer),
    ICON110("Travel Notification", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_travel_notification),
    ICON111("Unlock Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_unlock_regular),
    ICON112("Wallet Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_wallet_regular),
    ICON113("Wallet Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_wallet_solid),
    ICON114("X", ai.offside.mobile.android.component.ui.R.drawable.ic_decorative_x),
    ICON115("Make Payment Duotone", ai.offside.mobile.android.component.ui.R.drawable.ic_make_payment_duotone),
    ICON116("Placeholder Duotone", ai.offside.mobile.android.component.ui.R.drawable.ic_placeholder_duotone),
    ICON117("Profile With Big Circle", ai.offside.mobile.android.component.ui.R.drawable.ic_profile_with_bg_circle),
    ICON118("Rewards Duotone", ai.offside.mobile.android.component.ui.R.drawable.ic_rewards_duotone),
    ICON119("Security Big Circle", ai.offside.mobile.android.component.ui.R.drawable.ic_security_bg_circle),
    ICON120("Profile Alt", ai.offside.mobile.android.component.ui.R.drawable.ic_informative_profile_alt),
    ICON121("QR Code", ai.offside.mobile.android.component.ui.R.drawable.ic_informative_qr_code),
    ICON122("Paze", ai.offside.mobile.android.component.ui.R.drawable.ic_informative_paze),
    ICON123("Ecommerce", ai.offside.mobile.android.component.ui.R.drawable.ic_informative_ecommerce),
    ICON124("Check", ai.offside.mobile.android.component.ui.R.drawable.ic_informative_check),
    ICON125("Pin Angle Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_actionable_pin_angle_solid),
    ICON126("Pin Angle Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_actionable_pin_angle_regular),
    ICON127("Pin Straight Regular", ai.offside.mobile.android.component.ui.R.drawable.ic_actionable_pin_straight_regular),
    ICON128("Pin Straight Solid", ai.offside.mobile.android.component.ui.R.drawable.ic_actionable_pin_straight_solid),
}